### ISSUE TITLE
1 : 1 게임 매칭을 위한 기능 추가

### ISSUE THREAD

**Issue by flowjiyun** [august-thirty-first/frontend#87]
## 기능 명세
- [x] #160 PLAY 버튼 누르면 home.requestGeneralGame 이벤트 보내고 home.waitPlayer(너가 등록됐으니 기다릴 시간)이벤트만 오면 /general로 이동
- [x] #160 아무 때나 home.selectJoin(초대) 이벤트 오면 toast 뜨고 APPROVE 버튼 누르면 fromId 담은 쿼리스트링과 함께 /general로 이동
  - (단, toast에서 APPROVE 안하면 5초 뒤 toast 삭제해서 버튼에 접근 불가, 따로 refuse 이벤트는 가지 않음)
- [x] #161 /general로 오면 game소켓 연결됨 (Ladder와 동일하니 참고)
  - game.validateSocketGeneral 이벤트 보내서 체크하기
  - 쿼리스트링 같이 왔으면 game.generalGameApprove 이벤트 보내기
  - 기다리다가 game.matchGameFail(짝궁의 gameSocket이 어떤 이유로 끊겼을 때)이벤트 오면 openModal()(/profile로 이동)
  -  이 페이지에 머무른 시간이 5초가 넘으면 소켓 끊고 /profile로 이동 (옵션: '그만 기다리기' 버튼)
  - joinGame 이벤트 오면 /option으로 이동
- /option 페이지는 ladder가 사용하는 /option과 동일한 페이지 사용
## 예상 시간

**Comment by yeseulgangahan** [comment]
완료
